version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasaimasai666
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: sasaimasai666
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: sasaimasai666
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_CONFIG_EXTRA: define('WP_HOME', 'http://45.144.51.52:8080'); define('WP_SITEURL', 'http://45.144.51.52:8080');
    networks:
      - backend
      - frontend
    volumes:
      - wp-data:/var/www/html

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - wordpress
    ports:
      - "8080:80"  # Доступ по 45.144.51.52:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  mysql-data:
  wp-data:
